Comments Added
Pigmice2733/Bunnybot-2017 pull request #11
Opened 2017-11-29 00:30 UTC by MilanDonhowe

### I added some simple comments to try and explain the functionality of the python script.
I have never seen "bunnybot" before so most of the functionality of the script was inferred, if I was incorrect in any of the commented statements I would be happy to correct them.

2017-11-29 02:21 UTC, brendanburkhart requested changes

2017-11-29 02:21 UTC, BrendanBurkhart commented on components/bunnygrabber.py
> +# import Robot py library so this file can interface with the robot.
I think documenting our imports is unnecessary, this comment should be removed

2017-11-29 02:21 UTC, BrendanBurkhart commented on components/bunnygrabber.py
> +#	This program controls the bunny grabber arm.
We should be using Python [docstrings](https://www.python.org/dev/peps/pep-0257/) for documenting classes and functions, not comments

2017-11-29 02:21 UTC, BrendanBurkhart commented on components/bunnygrabber.py
> +# Class for controlling arm, will be instantiated in later script usage.
This doesn't control the whole arm, just the grabber at the end. This should become part of the classes docstring directly after the start of the class, also the comment about instantiating the class is unneeded.

2017-11-29 02:21 UTC, BrendanBurkhart commented on components/bunnygrabber.py
> +#	The following methods set_backward() and set_forward() tells the motor that
This comment should be split and added as a docstring (using `"""` triple quotes on each end) to each method individually.

2017-11-29 02:21 UTC, BrendanBurkhart commented on components/bunnygrabber.py
> +#   Method which allows the motor to move (or stop) based on if a direction has been specified with the previous methods.
This should also become a docstring right after the start of the method.

2017-11-29 02:21 UTC, BrendanBurkhart commented on components/bunnygrabber.py
> +
This should be condensed a bit, into something like "Sets motor direction based off the `direction` variable"

2017-11-30 23:02 UTC, calebeby requested changes

2017-11-30 23:02 UTC, calebeby commented on components/bunnygrabber.py
> +        """ Sets motor direction to forwards.
Since this is a single-line docstring, the end quotes should be on the same line. Try to follow https://www.python.org/dev/peps/pep-0257/

2017-11-30 23:03 UTC, calebeby commented on components/bunnygrabber.py
> +        """ Sets motor direction to forwards.
Also no space before/after

2017-11-30 23:13 UTC, calebeby requested changes

2017-11-30 23:13 UTC, calebeby commented on components/bunnygrabber.py
> +            Sets motor direction to backwards.
This is not a useful comment. It does not say anything that the code does not.

2017-11-30 23:13 UTC, calebeby commented on components/bunnygrabber.py
> +        """ Sets motor direction to forwards.
This is not a useful comment.

2017-12-01 00:21 UTC, brendanburkhart requested changes

2017-12-01 00:21 UTC, BrendanBurkhart commented on components/bunnygrabber.py
> +        """ Moves the motor based on the direction variable.
Anyone working with this code should already know what a components `execute` method does, or they should look it up. This behavior is essentially what every single execute does. This docstring should be split up and added as standard comments to the actual code within the `execute` method, `execute` doesn't need a docstring.

2017-12-01 06:35 UTC, MilanDonhowe commented
Since the code is self-explanatory I suppose it doesn't require documentation.
Not sure why I was asked to document this script.
I'll try and close the pull request.

2017-12-01 06:35 UTC, closed without merging

2017-12-01 15:35 UTC, calebeby commented
Yeah, sorry, most of the robot code is pretty self explanatory and doesn't need much documentation.