Documented the clamp function
Pigmice2733/Bunnybot-2017 pull request #16
Opened 2017-11-29 01:17 UTC by octoflo

2017-11-29 01:34 UTC, calebeby requested changes

2017-11-29 01:34 UTC, calebeby commented on utils.py
> +Standard utilies
At the top of the file is where you describe what kinds of things belong in this file, if it is not immediately obvious. I think `Standard utilities` is sufficient to describe the kinds of things that will be in this file.

Documentation for specific functions does not belong at the top of the file; instead, it belongs inside each function, at the top of each function.

2017-11-29 01:34 UTC, calebeby commented on utils.py
> +def clamp(value, max, min): # this function takes the input value and your specified range
It is unnecesary to repeat the parameters in a comment.

2017-11-29 01:34 UTC, calebeby commented on utils.py
> -    """Clamp value within a range"""
Why did you remove the function docstring?

2017-12-07 00:18 UTC, BrendanBurkhart commented
Closed due to inactivity

2017-12-07 00:18 UTC, closed without merging